### PR TITLE
fix bug in reduce.cu

### PR DESCRIPTION
**Pull request by hujie1008**

### CODE REVIEW

**Comment by ekelsen** [comment]
Do you have a description of the bug and/or inputs which demonstrate it?

I believe the code is correct as written, the function g is applied on line 76 inside the CTAreduce.

**Comment by hujie1008** [comment]
The function "reduce_rows" is called in function " ReduceHelper::impl". You can see that this code use 128 threads to do reduce. First, each thread do reduce_rows, and then CTAreduce try to reduce these 128 results. So g should be applied in both reduce_rows and CTAReduce. 

 When doing 'softmax', we should first minus the biggest element. So if  alphabet size is bigger than 128, this code will get wrong answer of the biggest element.

**Comment by DingKe** [comment]
The bug makes reduce_max return wrong results. I wonder why this PR not merged yet? @ekelsen

**Comment by ekelsen** [comment]
Thanks for providing the "test case" @DingKe .  And thanks @hujie1008 for the PR.

**Pull request merged**
